### ISSUE TITLE
Multi-Tenancy in Nanobus

### ISSUE THREAD

**Issue by fawadasaurus** [nanobus/nanobus#128]
**Is your feature request related to a problem? Please describe.**

I would like to be able to run multiple applications with a single NanoBus binary.  Each application would need to be isolated so the providers/resources are not able to be access across applications on the same NanoBus. Applications should be able to talk to each other over their public interfaces/transports. Each application should have its own tenant identifier so it is possible to determine which team/group is the owner of the application.

**Propose a solution**
NanoBus will need a `watch` functionality to continually poll for updates to the `applications.yaml` file and add/remove applications based on the changes done to the application.yaml file.

`nanobus run applications.yaml`

The application.yaml file would contain the following information:
```
applications:
  - tenant_id: abc123
    path: reg.candle.run/abc123/helloWorld:v0.0.1
    port_mappings: 
      - 80001:80
      - 80002:443
  - tenant_id: xyz987
    path: reg.candle.run/xyz987/helloMoon:v0.0.2
    port_mappings: 
      - 80003:80
```

Regarding `ports`: The goal here is that you can specify the ports the application runs. It should fail if the same port is attempted to be used across applications.  It should also fail if the application running needs more or less ports than are specified here.  So if the application needed only 1 port, it should fail to start this specific application and error to identify that only 1 port is required. It is not needed/expected that the ports are automatically generated by NanoBus as the infrastructure owner may want to have full understanding of their port usage and configurability.

Also needs API for checking status.

**Describe alternatives you've considered**

None

**Additional context**

None
