### ISSUE TITLE
Configuration requires top level fields even if they are empty

### ISSUE THREAD

**Issue by jsoverson** [nanobus/nanobus#24]
**Describe the bug**

When trying to define a bare minimum configuration for nanobus, nanobus will error out if certain fields are omitted even if they're supposed to be empty.

**Actual behavior**

```yaml
id: test
version: 0.0.1
authorization:
  sample:
    op:
      unauthenticated: true
interfaces:
  sample:
    op:
      steps:
        - name: Return value
          uses: assign
          with:
            value: '"test"'
```

```
$ echo '{}' | nanobus invoke bus.yaml --interface sample --operation op
2022-12-12T15:42:15.901-0500	ERROR	could not load configuration	{"file": "./bus.yaml", "error": "open : no such file or directory"}
```

**Expected behavior**

```
$ echo '{}' | nanobus invoke bus.yaml --interface sample --operation op
"test"
```

**To Reproduce**

Show Above

**Environment (where applicable):**

- OS: Mac OSX
- Architecture: m1
- Build Version: 

**Additional context** Add any other context about the problem here.
