### ISSUE TITLE
Nanobus doesn't complain with broken configuration

### ISSUE THREAD

**Issue by jsoverson** [nanobus/nanobus#34]
**Describe the bug**

Nanobus processes unknown fields or missing fields without complaining which is difficult to troubleshoot.

**To Reproduce**

Run `nanobus` with this config:

```yaml
id: your-app
version: 0.0.1
transports:
  http:
    uses: nanobus.transport.http.server/v1
    with:
      address: ':8080'
      routers:
        - uses: nanobus.transport.http.router/v1
          with:
            routes:
              - method: POST
                uri: /hello
                handler: greeter::say-hello
interfaces:
  greeter:
    say-hello:
      steps:
        - name: Say Hello!
          uses: assign
          with:
            value: '"Hello, " + input.name'
```

**Actual behavior**

Nanobus starts the http server and stays running.

**Expected behavior**

Nanobus should fail with an error message telling me it doesn't know what the `routers` key is.

**Environment (where applicable):**

- OS: Mac OS 12.6
- Architecture: m1
- Build Version: git
