### ISSUE TITLE
Update Package to add registry username and password in the yaml

### ISSUE THREAD

**Issue by fawadasaurus** [nanobus/nanobus#93]
**Is your feature request related to a problem? Please describe.**

Currently there is a proprietary naming convention for registries that must be followed that is not easy to follow.
```
  #export OCI_REGISTRIES=CANDLE
  #export CANDLE_HOSTNAME=reg.candle.run
  #export CANDLE_USERNAME=<your registry username>
  #export CANDLE_PASSWORD=<your registry password>
```

**Propose a solution**

Make it part of package in the yaml
```
package:
  registry: 
    host: reg.candle.run
    username: <can be from env variable>
    password: <can be from env variable>
  org: candle
```

**Describe alternatives you've considered**
None

**Additional context**
None
